version: '3'

services:
  nextjs:
    container_name: nextjs
    build:
      context: ./nextjs
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./nextjs/src:/app/src
      - ./nextjs/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - next_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  next_network:
    external: true
